image: docker.bestsens.de/bone/docker-build-image:2.0.3

variables:
    GIT_SUBMODULE_STRATEGY: recursive

stages:
    - build
    - build-image
    - deploy

.artifacts: &artifacts
    expire_in: 4 weeks
    name: "${CI_PROJECT_NAME}_${CI_COMMIT_REF_NAME}_${CI_COMMIT_SHA}"
    paths:
        - build/bemos_modbus
        - Dockerfile

## Build ##############################################################################################################
build:arm:
    image: docker.bestsens.de/bone/musl-build-image
    stage: build
    artifacts:
        <<: *artifacts
        name: "${CI_PROJECT_NAME}_${CI_COMMIT_REF_NAME}_${CI_COMMIT_SHA}_arm"
    cache:
        - key: "global_cache"
          paths:
            - .cache/
        - key: "${CI_COMMIT_REF_SLUG}_arm"
          paths:
            - build/
    script:
        - export CCACHE_DIR=${PWD}/.cache/ccache
        - mkdir -p build
        - cd build
        -   if [ "${CI_COMMIT_TAG}" == "" ]; then
                cmake .. -GNinja
                    -DGIT_BRANCH=${CI_COMMIT_REF_SLUG}
                    -DGIT_COMMIT_HASH=${CI_COMMIT_SHORT_SHA}
                    -DCPM_SOURCE_CACHE=../.cache/CPM
                    -DBUILD_TESTS=OFF
                    -DENABLE_WCONVERSION=OFF
                    -DCRITICAL_WARNINGS=OFF
                    -DCMAKE_TOOLCHAIN_FILE=../libs/bone_helper/cmake/arm-bemos-linux-musleabihf.cmake;
            else
                cmake .. -GNinja
                    -DCPM_SOURCE_CACHE=../.cache/CPM
                    -DBUILD_TESTS=OFF
                    -DENABLE_WCONVERSION=OFF
                    -DCRITICAL_WARNINGS=OFF
                    -DCMAKE_TOOLCHAIN_FILE=../libs/bone_helper/cmake/arm-bemos-linux-musleabihf.cmake;
            fi
        - ninja

build:i686:
    stage: build
    artifacts:
        <<: *artifacts
        name: "${CI_PROJECT_NAME}_${CI_COMMIT_REF_NAME}_${CI_COMMIT_SHA}_i686"
    cache:
        - key: "global_cache"
          paths:
            - .cache/
        - key: "${CI_COMMIT_REF_SLUG}_i686"
          paths:
            - build/
    script:
        - export CCACHE_DIR=${PWD}/.cache/ccache
        - mkdir -p build
        - cd build
        -   if [ "${CI_COMMIT_TAG}" == "" ]; then
                cmake .. -GNinja
                    -DGIT_BRANCH=${CI_COMMIT_REF_SLUG}
                    -DGIT_COMMIT_HASH=${CI_COMMIT_SHORT_SHA}
                    -DCPM_SOURCE_CACHE=../.cache/CPM
                    -DCRITICAL_WARNINGS=OFF
                    -DAUTORUN_TESTS=OFF; 
            else
                cmake .. -GNinja
                    -DCPM_SOURCE_CACHE=../.cache/CPM
                    -DCRITICAL_WARNINGS=OFF
                    -DAUTORUN_TESTS=OFF;
            fi
        - ninja

## Docker image #######################################################################################################
build-image:
    image: docker:latest
    stage: build-image
    variables:
        GIT_STRATEGY: none
    script:
        - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" "$CI_REGISTRY" --password-stdin
        - docker build --pull -t $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME .
        - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
    dependencies:
        - build:i686

release-image:
    image: docker:latest
    stage: deploy
    variables:
        GIT_STRATEGY: none
    script:
        - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" "$CI_REGISTRY" --password-stdin
        - docker pull $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
        - docker tag $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME $CI_REGISTRY_IMAGE:latest
        - docker push $CI_REGISTRY_IMAGE:latest
    only:
        - tags
    dependencies:
        - build-image

## Create persistent archives #########################################################################################
.deploy: &deploy
    stage: deploy
    when: on_success
    only:
        - tags
    variables:
        GIT_STRATEGY: none
    script:
        - echo '1'

deploy:arm:
    <<: *deploy
    artifacts:
        <<: *artifacts
        name: "${CI_PROJECT_NAME}_${CI_COMMIT_REF_NAME}_${CI_COMMIT_SHA}_arm"
        expire_in:
    dependencies:
        - build:arm

deploy:i686:
    <<: *deploy
    artifacts:
        <<: *artifacts
        name: "${CI_PROJECT_NAME}_${CI_COMMIT_REF_NAME}_${CI_COMMIT_SHA}_i686"
        expire_in:
    dependencies:
        - build:i686
